theme = "hugo-theme-casper"
baseURL = "https://wcchu.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
description = "some description"
publishDir = "/home/wei-chun/src/github.com/wcchu/wcchu.github.io"
